### ISSUE TITLE
Grafana Configuration [date_formats] not working

### ISSUE THREAD

**Issue by stefferber** [hassio-addons/addon-grafana#150]
Grafana charts shows date-time format in English as standard. I want to set this to ISO date-time standard. Grafana offers the option to use the [browser settings ](https://grafana.com/docs/grafana/latest/administration/configuration/#use_browser_locale)for this.
Therefore, I added this to Home Assistant Grafana configuration: Supervisor -> Add-Ons -> Grafana -> Configuration

```
plugins: []
env_vars:
  - name: GF_DEFAULT_INSTANCE_NAME
    value: Hass.io
  - name: GF_DATE_FORMATS_USE_BROWSER_LOCALE
    value: TRUE
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
```
<img width="961" alt="Bildschirmfoto 2021-05-07 um 19 19 24" src="https://user-images.githubusercontent.com/5459845/117486166-93247900-af69-11eb-83ca-e7014b656ad8.png">

when I press the save button (German "speichern") the two edited lines disappear:
```
plugins: []
env_vars:
  - name: GF_DEFAULT_INSTANCE_NAME
    value: Hass.io
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
```
<img width="952" alt="Bildschirmfoto 2021-05-07 um 19 19 48" src="https://user-images.githubusercontent.com/5459845/117486223-a9cad000-af69-11eb-84a1-c81053b9d76f.png">

and therefore the Grafana configuration does not change. 

<img width="625" alt="Bildschirmfoto 2021-05-07 um 19 24 19" src="https://user-images.githubusercontent.com/5459845/117486375-d8e14180-af69-11eb-8408-ab51fdd7573b.png">

What to do now?

**Comment by stefferber** [comment]
Thx @sinclairpaul for your super quick help and it solved my problem ;-)

```
plugins: []
env_vars:
  - name: GF_DEFAULT_INSTANCE_NAME
    value: Hass.io
  - name: GF_DATE_FORMATS_USE_BROWSER_LOCALE
    value: 'true'
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
```
<img width="595" alt="Bildschirmfoto 2021-05-08 um 10 00 02" src="https://user-images.githubusercontent.com/5459845/117531727-4762e580-afe4-11eb-8b58-51a62a338283.png">

Hence, it is very counter intuitive to declare a boolean as a string.  And deleting the configuration file changes without any hint is not so helpful either.
