### ISSUE TITLE
not able to create InfluxDB data source - origin not allowed

### ISSUE THREAD

**Issue by sql-aus-hh** [hassio-addons/addon-grafana#263]
# Problem/Motivation

I used Grafana as a separat docker container before, which worked great, but then i found this add-on and stopped my container. The only configuration I did was the mentioned ones in the documentations.

```
certfile: fullchain.pem
env_vars:
  - name: GF_AUTH_DISBALE_LOGIN_FORM
    value: 'true'
  - name: GF_AUTH_ANONYMOUS_ENABLED
    value: 'true'
  - name: GF_AUTH_ANONYMOUS_ORG_ROLE
    value: Admin
  - name: GF_SECURITY_ALLOW_EMBEDDING
    value: 'true'
keyfile: privkey.pem
plugins: []
ssl: true
```
But unfortunatley I am not able to add a data source "InfluxDB" with error message "Origin not allowed".

## Expected behavior

Adding a normal "InfluxDB" data source

## Actual behavior

error message - Origin not allowed
![image](https://user-images.githubusercontent.com/20439825/166239955-a4c17fc1-0649-4151-81d8-322d4f48af61.png)

## Proposed changes

Actually i don't know how to workaround, but there seems to be some new security features in the latest grafana version which causes these problems.
https://community.grafana.com/t/origin-not-allowed-messages-after-upgrade-to-8-3-6/60550/12
