### ISSUE TITLE
Installation of insigned Plugin fails

### ISSUE THREAD

**Issue by quizilkend** [hassio-addons/addon-grafana#358]
# Problem/Motivation

I try to install this plugin:
https://github.com/AutohomeCorp/autohome-compareQueries-datasource/

I followed the docs and have the following config:

```
custom_plugins:
  - name: Custom Compare Queries
    url: >-
      https://github.com/AutohomeCorp/autohome-compareQueries-datasource/archive/refs/tags/v1.0.1.zip
    unsigned: true
```

## Expected behavior

I can use the 3rd party plugin.

## Actual behavior

I see the following in the logs:
```
logger=plugin.loader t=2023-09-25T17:01:45.484232673+02:00 level=warn msg="Skipping loading plugin due to problem with signature" pluginID=autohome-comparequeries-datasource status=unsigned
```
