### ISSUE TITLE
Set value of admin password in config not working

### ISSUE THREAD

**Issue by kkellner** [hassio-addons/addon-grafana#67]
# Problem/Motivation

Trying to change the default `admin` user password.  The following does not work as value in `/etc/grafana/grafana.ini` within the container still shows `hassio`

```
plugins: []
env_vars:
  - name: GF_SECURITY_ADMIN_PASSWORD
    value: test
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
log_level: info
grafana_ingress_user: myuser
```

## Expected behavior

The `admin` user password is updated to the value specified.

## Actual behavior

Default password remains

## Steps to reproduce

Use the above config, setting the value of `GF_SECURITY_ADMIN_PASSWORD` and restart the container.   The default password is not updated.
