### ISSUE TITLE
Additional environment variables cannot be added

### ISSUE THREAD

**Issue by bithajcsar** [hassio-addons/addon-grafana#84]
# Problem/Motivation

I need to override the anonymous authentication setting. Once it is not possible to edit the grafana.ini, I tried to add an environment variable to override it.
Environment: HASSIO on a RasPi 4 (4GB)

## Expected behavior

Accept the modified configuration and allow anonymous access.

## Actual behavior

If I write in the config page

```
env_vars:
  - name: GF_DEFAULT_INSTANCE_NAME
    value: Hassio
  - name: GF_AUTH_ANONYMOUS_ENABLED
    value: true
```

I get:

`Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'plugins': ['grafana-clock-panel'], 'env_vars': [{'name': 'GF_DEFAULT_INSTANCE_NAME', 'value': 'Hassio'}, {'name': 'GF_AUTH_ANONYMOUS_ENABLED', 'value': True}], 'ssl': False, 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem'}
`
## Steps to reproduce

Try to modify the configuration as shown above.

## Proposed changes

Check the config parser/implementer for accepting additional env. vars.

**Comment by bithajcsar** [comment]
I figured out myself:
Value "true" must be between apostrophes:

```
env_vars:
  - name: GF_DEFAULT_INSTANCE_NAME
    value: Hassio
  - name: GF_AUTH_ANONYMOUS_ENABLED
    value: 'true'

```

Would be useful to mention it somewhere in the documentation!
