### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by Toukite** [hassio-addons/addon-grafana#99]
# Problem/Motivation

> Hi, I just wanted to highlight that current configuration in documentation does not seem to work, even if setting user to admin instead of frenck and even if removing plugins (not sure how to install those on a HassOS setup):
```
log_level: info
grafana_ingress_user: frenck
plugins:
  - ayoungprogrammer-finance-datasource
  - grafana-clock-panel
env_vars:
  - name: GF_DEFAULT_INSTANCE_NAME
    value: Hassio
```

However it works with the default configuration (present when installing the addon):
```
plugins: []
env_vars: []
ssl: true
certfile: cert.pem
keyfile: privkey.pem
```

## Expected behavior

> Config successfully saved and addon starting properly when based upon documentation

## Actual behavior

> Following error appears when saving the config:
`Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'log_level': 'info', 'grafana_ingress_user': 'admin', 'plugins': ['ayoungprogrammer-finance-datasource', 'grafana-clock-panel'], 'env_vars': [{'name': 'GF_DEFAULT_INSTANCE_NAME', 'value': 'Hassio'}]}`

## Steps to reproduce

> Install Grafana and try to save the documented configuration

## Proposed changes

> Make the proposed documentation a workable basis. 
> Currently, some options present in the default config after addon installation are not documented + the opposite: some options documented do not seem to work if put in the actual configuration
